USE [master]
GO

/****** Object:  Database [DB_PatrimonyManagement]    Script Date: 20/01/2019 20:34:38 ******/
CREATE DATABASE [DB_PatrimonyManagement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_PatrimonyManagement', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\DB_PatrimonyManagement.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_PatrimonyManagement_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\DB_PatrimonyManagement_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_PatrimonyManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_PatrimonyManagement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET  MULTI_USER 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_PatrimonyManagement] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_PatrimonyManagement] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DB_PatrimonyManagement] SET  READ_WRITE 
GO


